---------------------------------------------------------------------------------------------------------------
# Data Overview
---------------------------------------------------------------------------------------------------------------
## Content log:
01. Import Libraries
02. Load Data
03. Data Overview
04. Missing Values Analysis
05. Checking Duplicated Values
06. Basic Statistics
07. Unique Value Check
08. Key Observations
---------------------------------------------------------------------------------------------------------------

# 01. Import Libraries

In [1]:
import os
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# 02. Load Data

In [3]:
data_path = "../../data/raw_data"
datasets = {}
for file in os.listdir(data_path):
    if file.endswith(".csv"):
        df = pd.read_csv(os.path.join(data_path, file))
        df["Ticker"] = file.replace(".csv", "")
        datasets[file] = df
print(f"Total datasets loaded: {len(datasets)}")

Total datasets loaded: 30

# 03. Dataset Overview

In [4]:

for name, df in datasets.items():
    print("="*60)
    print(f"Dataset: {name}")
    print("="*60)    
    print("\nShape:")
    print(df.shape)
    print("\nColumns:")
    print(df.columns.tolist())
    print("\nData Types:")
    print(df.dtypes)
    print("\nFirst 5 Rows:")
    display(df.head())

============================================================
Dataset: ADANIENT_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open    Volume       Ticker
0  3/2/2016  32.988026  33.833198  32.274916  32.750322   9313684  ADANIENT_NS
1  3/3/2016  33.014435  33.542664  32.406969  33.278549   7706783  ADANIENT_NS
2  3/4/2016  33.384197  34.150133  33.014439  33.278553   9013442  ADANIENT_NS
3  3/8/2016  33.833191  34.070894  32.882374  33.542662  11091171  ADANIENT_NS
4  3/9/2016  35.074535  35.312239  33.331372  33.542664   7364105  ADANIENT_NS

============================================================
Dataset: ADANIPORTS_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume         Ticker
0  3/2/2016  207.282257  210.834855  197.856033  197.998131  4228824  ADANIPORTS_NS
1  3/3/2016  215.524246  217.371594  206.192751  209.224312  3290989  ADANIPORTS_NS
2  3/4/2016  213.297974  216.803215  210.503266  216.803215  4768604  ADANIPORTS_NS
3  3/8/2016  216.234772  219.503159  210.597986  212.208495  3066086  ADANIPORTS_NS
4  3/9/2016  214.103226  220.403160  209.650639  215.997944  4117976  ADANIPORTS_NS

============================================================
Dataset: ASIANPAINT_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume         Ticker
0  3/2/2016  803.808289  812.198132  798.875840  807.634433   808137  ASIANPAINT_NS
1  3/3/2016  811.552918  826.534724  803.716280  806.159490  1061326  ASIANPAINT_NS
2  3/4/2016  798.230530  820.634078  791.408080  817.407228  1039977  ASIANPAINT_NS
3  3/8/2016  807.357910  812.981826  791.085344  800.166655  1174011  ASIANPAINT_NS
4  3/9/2016  807.818909  819.435547  801.964447  807.634506  1401934  ASIANPAINT_NS

============================================================
Dataset: AXISBANK_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume       Ticker
0  3/2/2016  397.396576  401.836477  390.321990  390.321990  15332044  AXISBANK_NS
1  3/3/2016  407.057037  408.862282  397.250209  401.397380  14677533  AXISBANK_NS
2  3/4/2016  405.983673  408.032870  399.348211  408.032870   8992492  AXISBANK_NS
3  3/8/2016  401.787720  412.814305  398.909083  405.544575   6921273  AXISBANK_NS
4  3/9/2016  406.764282  408.081625  397.640500  399.104208   8437253  AXISBANK_NS

============================================================
Dataset: BAJAJFINSV_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume         Ticker
0  3/2/2016  170.960159  172.651846  168.273361  169.074419   551440  BAJAJFINSV_NS
1  3/3/2016  166.701080  172.741399  164.755636  171.497510   475900  BAJAJFINSV_NS
2  3/4/2016  166.233368  169.666499  165.412404  169.034609   255700  BAJAJFINSV_NS
3  3/8/2016  166.158722  167.974797  165.288000  167.974797  1716350  BAJAJFINSV_NS
4  3/9/2016  166.999618  167.875306  166.178639  167.079214   168760  BAJAJFINSV_NS

============================================================
Dataset: BAJFINANCE_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open    Volume         Ticker
0  3/2/2016  61.666142  63.002856  60.432023  60.786289  12220100  BAJFINANCE_NS
1  3/3/2016  60.086472  62.044602  59.816418  61.763904   6545100  BAJFINANCE_NS
2  3/4/2016  61.314301  61.821980  59.566695  60.970200   4627500  BAJFINANCE_NS
3  3/8/2016  60.912605  62.264329  60.729183  61.365114   5294900  BAJFINANCE_NS
4  3/9/2016  62.178177  62.673760  60.065661  60.931479   6285900  BAJFINANCE_NS

============================================================
Dataset: BHARTIARTL_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume         Ticker
0  3/2/2016  278.596710  279.791844  274.029561  274.883224  3289694  BHARTIARTL_NS
1  3/3/2016  284.615173  285.938363  276.590618  280.346799  3265002  BHARTIARTL_NS
2  3/4/2016  281.072357  287.389557  279.236947  283.419960  2167900  BHARTIARTL_NS
3  3/8/2016  282.993195  285.127382  278.938236  281.285839  2393678  BHARTIARTL_NS
4  3/9/2016  285.639526  286.706634  280.261379  280.901656  3430173  BHARTIARTL_NS

============================================================
Dataset: DRREDDY_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume      Ticker
0  3/2/2016  563.875610  575.030626  562.145810  570.355428  1842655  DRREDDY_NS
1  3/3/2016  596.209412  598.612471  572.618376  572.618376  4450185  DRREDDY_NS
2  3/4/2016  608.290100  613.947079  598.425442  601.034183  2963165  DRREDDY_NS
3  3/8/2016  602.081360  611.515935  596.181262  609.645856  1503355  DRREDDY_NS
4  3/9/2016  602.156189  603.306269  593.637991  602.352568  1751980  DRREDDY_NS

============================================================
Dataset: EICHERMOT_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date        Close         High          Low         Open   Volume        Ticker
0  3/2/2016  1791.086792  1807.596225  1781.937579  1807.596225   738640  EICHERMOT_NS
1  3/3/2016  1791.689331  1801.200077  1784.607248  1801.107402   450450  EICHERMOT_NS
2  3/4/2016  1785.209839  1798.326521  1770.610023  1798.326521   232010  EICHERMOT_NS
3  3/8/2016  1835.595581  1853.481557  1775.152379  1779.787241  1035450  EICHERMOT_NS
4  3/9/2016  1847.803589  1879.204779  1833.315006  1838.742411   799690  EICHERMOT_NS

============================================================
Dataset: HCLTECH_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume      Ticker
0  3/2/2016  323.980530  327.827299  314.316257  317.215548   3279278  HCLTECH_NS
1  3/3/2016  325.667145  328.339028  322.748908  327.827399   2015842  HCLTECH_NS
2  3/4/2016  316.609283  326.349340  314.695359  326.008261   3554776  HCLTECH_NS
3  3/8/2016  308.972595  315.301753  306.774451  313.804733   6490012  HCLTECH_NS
4  3/9/2016  309.124176  310.014796  303.704584  308.479886  12221478  HCLTECH_NS

============================================================
Dataset: HDFCBANK_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume       Ticker
0  3/2/2016  231.546707  232.397309  228.742028  229.431703  6358976  HDFCBANK_NS
1  3/3/2016  233.535233  234.489288  232.190373  232.362792  4610400  HDFCBANK_NS
2  3/4/2016  234.615738  235.615774  228.305214  233.443297  5704624  HDFCBANK_NS
3  3/8/2016  233.144424  235.408850  232.075424  235.408850  1913688  HDFCBANK_NS
4  3/9/2016  235.592773  236.765214  231.443221  232.880043  6528172  HDFCBANK_NS

============================================================
Dataset: HINDUNILVR_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume         Ticker
0  3/2/2016  722.430908  727.322257  706.055524  706.055524  1221727  HINDUNILVR_NS
1  3/3/2016  722.133301  728.258079  719.453671  727.747698   746384  HINDUNILVR_NS
2  3/4/2016  722.005615  728.087922  715.795739  721.792948  1331537  HINDUNILVR_NS
3  3/8/2016  702.865540  721.367598  700.951533  721.367598  1342346  HINDUNILVR_NS
4  3/9/2016  714.264587  717.879932  703.120787  703.120787  1929618  HINDUNILVR_NS

============================================================
Dataset: ICICIBANK_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume        Ticker
0  3/2/2016  186.765900  187.954404  179.210367  179.719730  40766551  ICICIBANK_NS
1  3/3/2016  185.068054  187.020595  181.842084  185.577403  22903720  ICICIBANK_NS
2  3/4/2016  187.190384  190.501236  185.959432  188.251558  24493722  ICICIBANK_NS
3  3/8/2016  184.091766  186.723463  181.926971  186.723463  18883002  ICICIBANK_NS
4  3/9/2016  183.667297  184.983146  178.318994  180.653568  17300650  ICICIBANK_NS

============================================================
Dataset: INFY_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume   Ticker
0  3/2/2016  441.206085  444.068581  429.374434  433.973530  7214898  INFY_NS
1  3/3/2016  446.282227  455.270436  440.442716  445.786042  5814304  INFY_NS
2  3/4/2016  446.797455  452.274354  442.389192  448.686684  4281680  INFY_NS
3  3/8/2016  444.049408  454.373495  437.923695  443.877677  7617746  INFY_NS
4  3/9/2016  449.793488  451.797235  436.225239  437.007674  6305782  INFY_NS

============================================================
Dataset: ITC_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume  Ticker
0  3/2/2016  143.239304  149.671743  142.746230  147.027043  24680589  ITC_NS
1  3/3/2016  142.611725  145.682255  141.984166  144.785747  10227569  ITC_NS
2  3/4/2016  141.289383  144.225439  141.087666  143.440998  11818471  ITC_NS
3  3/8/2016  143.553070  145.234019  141.647997  141.647997  13109801  ITC_NS
4  3/9/2016  143.396210  143.754809  140.168786  142.096277  20903665  ITC_NS

============================================================
Dataset: KOTAKBANK_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume        Ticker
0  3/2/2016  130.410934  131.136223  127.509824  128.612645  6218455  KOTAKBANK_NS
1  3/3/2016  130.679169  131.444192  129.149137  130.748723  4612120  KOTAKBANK_NS
2  3/4/2016  132.268860  133.103423  128.165570  130.748758  3582405  KOTAKBANK_NS
3  3/8/2016  129.268372  132.298645  128.771606  132.129747  3317790  KOTAKBANK_NS
4  3/9/2016  131.126267  131.970774  128.702047  129.149149  4064310  KOTAKBANK_NS

============================================================
Dataset: LT_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume Ticker
0  3/2/2016  648.860535  656.273494  646.180499  651.768710  3652203  LT_NS
1  3/3/2016  688.320252  690.658183  646.893292  655.133087  5552958  LT_NS
2  3/4/2016  680.394165  697.928627  676.858737  692.825094  3438969  LT_NS
3  3/8/2016  677.115478  691.114515  668.989751  684.842041  3022782  LT_NS
4  3/9/2016  691.599060  695.676175  671.726667  674.235677  3121141  LT_NS

============================================================
Dataset: MARUTI_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date        Close         High          Low         Open   Volume     Ticker
0  3/2/2016  3298.447266  3312.188368  3232.161632  3234.809321  1236996  MARUTI_NS
1  3/3/2016  3294.794922  3329.809598  3266.810732  3310.453469   742263  MARUTI_NS
2  3/4/2016  3245.902588  3304.244928  3219.333411  3304.244928   610234  MARUTI_NS
3  3/8/2016  3161.492920  3285.938547  3150.491123  3243.939304  1100041  MARUTI_NS
4  3/9/2016  3265.349854  3286.897381  3141.817472  3154.371594   752948  MARUTI_NS

============================================================
Dataset: NESTLEIND_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume        Ticker
0  3/2/2016  223.881226  225.062747  222.417543  223.960578   582760  NESTLEIND_NS
1  3/3/2016  230.033524  231.146697  223.960566  225.283168   662200  NESTLEIND_NS
2  3/4/2016  233.009323  234.763966  227.751961  230.044475   525820  NESTLEIND_NS
3  3/8/2016  234.576584  239.346769  232.605894  233.659573  1070940  NESTLEIND_NS
4  3/9/2016  229.682953  233.988027  228.457356  232.570654   942460  NESTLEIND_NS

============================================================
Dataset: NTPC_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open   Volume   Ticker
0  3/2/2016  73.274002  73.822983  70.673584  71.482606  7180521  NTPC_NS
1  3/3/2016  73.042862  74.458643  72.782820  73.967452  4161891  NTPC_NS
2  3/4/2016  72.840591  73.765186  71.655960  73.678506  7395987  NTPC_NS
3  3/8/2016  73.707420  73.967462  71.944916  72.811722  4202145  NTPC_NS
4  3/9/2016  73.129532  73.794080  72.869490  73.562935  4332384  NTPC_NS

============================================================
Dataset: ONGC_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open    Volume   Ticker
0  3/2/2016  76.099861  77.017206  74.987351  75.885173  15524956  ONGC_NS
1  3/3/2016  76.978142  78.402941  75.631422  76.704897  16866745  ONGC_NS
2  3/4/2016  78.344406  79.788718  77.680802  78.032117  22523046  ONGC_NS
3  3/8/2016  78.793312  80.549913  78.461510  79.144636  12258796  ONGC_NS
4  3/9/2016  80.120522  80.413288  78.578617  78.851871   7688815  ONGC_NS

============================================================
Dataset: POWERGRID_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open    Volume        Ticker
0  3/2/2016  48.135250  49.130659  47.655319  47.993045  13550709  POWERGRID_NS
1  3/3/2016  48.224140  48.668520  47.655333  48.526315   7057560  POWERGRID_NS
2  3/4/2016  49.290642  49.468394  48.153027  48.490758  29228314  POWERGRID_NS
3  3/8/2016  48.952911  49.663919  48.384104  49.592817  20131612  POWERGRID_NS
4  3/9/2016  49.681694  49.841673  48.561857  48.668511   7284193  POWERGRID_NS

============================================================
Dataset: RELIANCE_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume       Ticker
0  3/2/2016  217.008957  217.929866  213.921212  215.145470  20105967  RELIANCE_NS
1  3/3/2016  219.468338  220.584257  216.142233  218.850777  15880459  RELIANCE_NS
2  3/4/2016  218.070709  219.934196  217.442329  219.717503   8987660  RELIANCE_NS
3  3/8/2016  222.534393  223.379451  218.309047  218.309047  13222993  RELIANCE_NS
4  3/9/2016  225.719635  226.196340  220.714235  221.017598  11854901  RELIANCE_NS

============================================================
Dataset: SBIN_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open    Volume   Ticker
0  3/2/2016  163.504471  165.354786  155.697059  155.697059  53333757  SBIN_NS
1  3/3/2016  164.948608  166.618408  161.112594  166.076848  33507048  SBIN_NS
2  3/4/2016  170.048233  171.357002  161.112583  165.535276  38860711  SBIN_NS
3  3/8/2016  165.490173  168.739495  163.730109  168.739495  27928279  SBIN_NS
4  3/9/2016  165.535278  166.076839  161.293101  162.466473  29453018  SBIN_NS

============================================================
Dataset: SUNPHARMA_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume        Ticker
0  3/2/2016  782.693237  805.893337  780.993450  804.882662  3184958  SUNPHARMA_NS
1  3/3/2016  800.196716  802.907178  783.382342  790.089742  2447143  SUNPHARMA_NS
2  3/4/2016  787.241516  803.504570  783.382478  801.207530  1525260  SUNPHARMA_NS
3  3/8/2016  788.895325  800.288664  782.142050  789.997915  2297582  SUNPHARMA_NS
4  3/9/2016  791.008728  793.581402  768.957144  790.181771  3139226  SUNPHARMA_NS

============================================================
Dataset: TCS_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume  Ticker
0  3/2/2016  917.165955  921.576033  892.405976  911.687878  1527486  TCS_NS
1  3/3/2016  938.642944  945.703126  910.105768  923.949185  2648284  TCS_NS
2  3/4/2016  932.472595  941.352137  929.308386  941.352137  1512966  TCS_NS
3  3/8/2016  931.187195  936.210357  911.371297  926.361795  1268152  TCS_NS
4  3/9/2016  932.354248  937.159853  907.792029  925.926946  2017784  TCS_NS

============================================================
Dataset: TECHM_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume    Ticker
0  3/2/2016  328.779785  332.532741  313.262793  316.438381  2339747  TECHM_NS
1  3/3/2016  333.254456  334.878327  326.362033  331.774937  2371409  TECHM_NS
2  3/4/2016  325.676453  333.434950  324.738225  331.991509  2756908  TECHM_NS
3  3/8/2016  323.944336  331.666734  321.165707  328.382914  2050957  TECHM_NS
4  3/9/2016  334.986603  337.404371  319.072673  320.371761  4030260  TECHM_NS

============================================================
Dataset: TITAN_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date       Close        High         Low        Open   Volume    Ticker
0  3/2/2016  320.992950  325.367086  314.840351  324.453797  1520145  TITAN_NS
1  3/3/2016  328.924042  331.183207  319.599017  320.127745  1501530  TITAN_NS
2  3/4/2016  325.367004  332.048330  323.011699  328.683625   893896  TITAN_NS
3  3/8/2016  328.347229  330.702535  323.204059  324.934467  2006420  TITAN_NS
4  3/9/2016  326.712982  328.347250  324.165425  328.347250   914711  TITAN_NS

============================================================
Dataset: ULTRACEMCO_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date        Close         High          Low         Open  Volume         Ticker
0  3/2/2016  2853.544678  2882.339276  2784.005770  2802.674221  481863  ULTRACEMCO_NS
1  3/3/2016  2825.949951  2889.058114  2818.127512  2879.459915  376438  ULTRACEMCO_NS
2  3/4/2016  2790.100586  2844.714483  2778.966815  2830.509101  184854  ULTRACEMCO_NS
3  3/8/2016  2831.468750  2836.267850  2792.404126  2801.714333  365340  ULTRACEMCO_NS
4  3/9/2016  2871.397949  2880.372127  2831.517377  2840.011644  482513  ULTRACEMCO_NS

============================================================
Dataset: WIPRO_NS.csv
============================================================

Shape:
(2470, 7)

Columns:
['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Ticker']

Data Types:
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
Ticker     object
dtype: object

First 5 Rows:

       Date      Close       High        Low       Open    Volume    Ticker
0  3/2/2016  91.750740  92.141857  90.152269  91.827261   9548461  WIPRO_NS
1  3/3/2016  92.286392  93.264182  91.019518  91.852769   6511139  WIPRO_NS
2  3/4/2016  91.308601  92.788046  90.994012  92.660508   8533469  WIPRO_NS
3  3/8/2016  92.073807  92.422411  90.840941  91.436118   8277325  WIPRO_NS
4  3/9/2016  91.512665  92.167355  90.679414  92.167355  10597186  WIPRO_NS

# 04. Missing Values Analysis

In [6]:
for name, df in datasets.items():
    print("="*60)
    print(f"Missing Values: {name}")
    print("="*60)
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing)

============================================================
Missing Values: ADANIENT_NS.csv
============================================================
No missing values
============================================================
Missing Values: ADANIPORTS_NS.csv
============================================================
No missing values
============================================================
Missing Values: ASIANPAINT_NS.csv
============================================================
No missing values
============================================================
Missing Values: AXISBANK_NS.csv
============================================================
No missing values
============================================================
Missing Values: BAJAJFINSV_NS.csv
============================================================
No missing values
============================================================
Missing Values: BAJFINANCE_NS.csv
============================================================
No missing values
============================================================
Missing Values: BHARTIARTL_NS.csv
============================================================
No missing values
============================================================
Missing Values: DRREDDY_NS.csv
============================================================
No missing values
============================================================
Missing Values: EICHERMOT_NS.csv
============================================================
No missing values
============================================================
Missing Values: HCLTECH_NS.csv
============================================================
No missing values
============================================================
Missing Values: HDFCBANK_NS.csv
============================================================
No missing values
============================================================
Missing Values: HINDUNILVR_NS.csv
============================================================
No missing values
============================================================
Missing Values: ICICIBANK_NS.csv
============================================================
No missing values
============================================================
Missing Values: INFY_NS.csv
============================================================
No missing values
============================================================
Missing Values: ITC_NS.csv
============================================================
No missing values
============================================================
Missing Values: KOTAKBANK_NS.csv
============================================================
No missing values
============================================================
Missing Values: LT_NS.csv
============================================================
No missing values
============================================================
Missing Values: MARUTI_NS.csv
============================================================
No missing values
============================================================
Missing Values: NESTLEIND_NS.csv
============================================================
No missing values
============================================================
Missing Values: NTPC_NS.csv
============================================================
No missing values
============================================================
Missing Values: ONGC_NS.csv
============================================================
No missing values
============================================================
Missing Values: POWERGRID_NS.csv
============================================================
No missing values
============================================================
Missing Values: RELIANCE_NS.csv
============================================================
No missing values
============================================================
Missing Values: SBIN_NS.csv
============================================================
No missing values
============================================================
Missing Values: SUNPHARMA_NS.csv
============================================================
No missing values
============================================================
Missing Values: TCS_NS.csv
============================================================
No missing values
============================================================
Missing Values: TECHM_NS.csv
============================================================
No missing values
============================================================
Missing Values: TITAN_NS.csv
============================================================
No missing values
============================================================
Missing Values: ULTRACEMCO_NS.csv
============================================================
No missing values
============================================================
Missing Values: WIPRO_NS.csv
============================================================
No missing values

# 05. Checking Duplicated Values

In [7]:
for name, df in datasets.items():
    duplicates = df.duplicated().sum()
    print(f"{name} -> Duplicate Rows: {duplicates}")

ADANIENT_NS.csv -> Duplicate Rows: 0
ADANIPORTS_NS.csv -> Duplicate Rows: 0
ASIANPAINT_NS.csv -> Duplicate Rows: 0
AXISBANK_NS.csv -> Duplicate Rows: 0
BAJAJFINSV_NS.csv -> Duplicate Rows: 0
BAJFINANCE_NS.csv -> Duplicate Rows: 0
BHARTIARTL_NS.csv -> Duplicate Rows: 0
DRREDDY_NS.csv -> Duplicate Rows: 0
EICHERMOT_NS.csv -> Duplicate Rows: 0
HCLTECH_NS.csv -> Duplicate Rows: 0
HDFCBANK_NS.csv -> Duplicate Rows: 0
HINDUNILVR_NS.csv -> Duplicate Rows: 0
ICICIBANK_NS.csv -> Duplicate Rows: 0
INFY_NS.csv -> Duplicate Rows: 0
ITC_NS.csv -> Duplicate Rows: 0
KOTAKBANK_NS.csv -> Duplicate Rows: 0
LT_NS.csv -> Duplicate Rows: 0
MARUTI_NS.csv -> Duplicate Rows: 0
NESTLEIND_NS.csv -> Duplicate Rows: 0
NTPC_NS.csv -> Duplicate Rows: 0
ONGC_NS.csv -> Duplicate Rows: 0
POWERGRID_NS.csv -> Duplicate Rows: 0
RELIANCE_NS.csv -> Duplicate Rows: 0
SBIN_NS.csv -> Duplicate Rows: 0
SUNPHARMA_NS.csv -> Duplicate Rows: 0
TCS_NS.csv -> Duplicate Rows: 0
TECHM_NS.csv -> Duplicate Rows: 0
TITAN_NS.csv -> Duplicate Rows: 0
ULTRACEMCO_NS.csv -> Duplicate Rows: 0
WIPRO_NS.csv -> Duplicate Rows: 0

# 06. Basic Statistics

In [10]:
for name, df in datasets.items():
    print("="*60)
    print(f"Statistical Summary: {name}")
    print("="*60)
    
    display(df.describe())

============================================================
Statistical Summary: ADANIENT_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1269.420366  1291.934146  1248.342980  1271.869465  6.127435e+06
std    1226.836184  1246.403139  1209.534061  1230.282957  9.182199e+06
min      32.906822    33.413899    31.145383    31.919348  0.000000e+00
25%     122.666697   125.825326   117.965612   122.356241  1.670581e+06
50%     871.109039   891.035666   852.928221   868.889447  3.653136e+06
75%    2385.621582  2420.470085  2352.688464  2395.816255  6.948777e+06
max    4159.593750  4184.260452  4060.829331  4169.281000  1.701502e+08

============================================================
Statistical Summary: ADANIPORTS_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    673.903555   683.957267   664.305025   674.995695  5.501982e+06
std     405.764944   410.668716   401.409945   406.573590  7.204562e+06
min     163.255951   171.678072   161.495388   163.303544  0.000000e+00
25%     350.554146   355.725224   345.565665   351.413330  2.381238e+06
50%     571.872375   585.603212   553.613800   571.635775  3.586992e+06
75%     839.340866   859.257063   826.986111   841.457015  5.851112e+06
max    1582.451172  1606.656410  1560.905968  1575.900024  1.155175e+08

============================================================
Statistical Summary: ASIANPAINT_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   2082.829187  2104.857535  2061.020851  2084.226384  1.309598e+06
std     832.501464   839.872507   824.908312   833.337591  9.711016e+05
min     779.422729   790.025040   776.933433   781.266494  0.000000e+00
25%    1229.643830  1247.141217  1212.057783  1227.976283  7.302278e+05
50%    2258.777222  2278.662567  2234.835812  2256.928390  1.031296e+06
75%    2882.014832  2910.717305  2859.645068  2886.878765  1.571338e+06
max    3460.254883  3483.982728  3422.466044  3464.355850  1.154592e+07

============================================================
Statistical Summary: AXISBANK_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    765.932800   775.040798   756.897068   766.218205  1.131986e+07
std     256.591634   257.796459   255.345525   256.490430  9.671030e+06
min     301.889465   336.096641   284.810793   292.279607  0.000000e+00
25%     536.926102   543.460952   529.379435   536.789299  6.029193e+06
50%     726.317322   734.881623   717.454358   727.387904  8.323056e+06
75%     976.536148   985.669412   967.176330   976.561585  1.248267e+07
max    1403.000000  1418.300049  1387.599976  1403.000000  1.205419e+08

============================================================
Statistical Summary: BAJAJFINSV_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1099.777283  1114.027254  1086.243965  1100.838997  2.819291e+06
std     585.676827   591.489931   580.222559   586.303482  3.349275e+06
min     163.690888   165.198481   161.034371   163.868421  0.000000e+00
25%     558.062225   568.153438   550.128968   559.493400  1.153382e+06
50%     972.456024   984.215779   959.027421   972.896201  1.808381e+06
75%    1625.813294  1644.231020  1609.212022  1627.286077  3.158958e+06
max    2176.600098  2195.000000  2159.100098  2176.600098  4.110412e+07

============================================================
Statistical Summary: BAJFINANCE_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    483.026241   489.195518   476.934841   483.289442  1.869561e+07
std     276.953166   279.627222   274.449366   276.939321  2.460262e+07
min      60.086472    61.821980    59.566695    60.786289  0.000000e+00
25%     221.662537   227.312652   215.823702   221.488306  7.487525e+06
50%     517.260895   524.943088   508.941933   518.188999  1.105757e+07
75%     706.701950   714.304811   699.496042   706.914142  1.811250e+07
max    1094.150024  1102.500000  1087.400024  1093.500000  2.596005e+08

============================================================
Statistical Summary: BHARTIARTL_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    748.172044   756.920359   739.528928   748.501095  8.985938e+06
std     531.292995   535.398750   527.270339   531.397193  1.114409e+07
min     248.379013   252.426553   240.980330   246.377009  0.000000e+00
25%     331.418327   336.330433   326.121038   331.730694  3.896080e+06
50%     529.832336   538.897342   522.264351   530.772057  5.888192e+06
75%     873.632462   880.072835   867.126911   873.520228  9.993229e+06
max    2162.699951  2174.500000  2149.899902  2162.100098  1.985470e+08

============================================================
Statistical Summary: DRREDDY_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    821.713162   830.960205   812.843739   822.518797  3.209322e+06
std     298.892306   301.282712   296.382002   299.253667  4.059116e+06
min     358.653473   371.991334   357.507260   360.443896  0.000000e+00
25%     532.289749   538.583336   526.129929   532.684543  1.422565e+06
50%     843.108032   852.346086   835.236766   843.932463  2.155838e+06
75%    1082.251678  1093.896006  1071.902265  1084.360770  3.695731e+06
max    1403.588257  1412.531537  1384.290601  1403.568315  1.099354e+08

============================================================
Statistical Summary: EICHERMOT_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   3088.422543  3127.355840  3050.579398  3090.078650  8.701461e+05
std    1393.885182  1403.368044  1381.610437  1391.687507  8.596553e+05
min    1208.917725  1248.946268  1186.994172  1236.199137  0.000000e+00
25%    2118.589905  2143.917390  2081.072684  2117.207826  3.840385e+05
50%    2630.215454  2663.763921  2601.162796  2635.538800  5.933210e+05
75%    3457.316407  3508.250659  3412.704609  3460.270308  1.047604e+06
max    8190.000000  8230.000000  8024.500000  8220.000000  1.431668e+07

============================================================
Statistical Summary: HCLTECH_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    818.543752   827.848380   809.545438   818.949588  3.910370e+06
std     471.691867   476.298563   467.122826   471.808614  2.910774e+06
min     270.814392   273.890304   269.916463   271.674120  0.000000e+00
25%     383.474190   388.828261   378.706161   384.233422  2.223940e+06
50%     779.423340   788.208853   771.661378   780.012515  3.112352e+06
75%    1128.055664  1137.154215  1107.960734  1121.740612  4.651092e+06
max    1908.191528  1924.546485  1879.785210  1908.000161  3.231247e+07

============================================================
Statistical Summary: HDFCBANK_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    624.843365   630.251908   619.362863   624.890312  1.937598e+07
std     201.654459   203.119383   200.397514   201.650099  2.163453e+07
min     231.546707   232.397309   228.305214   229.431703  0.000000e+00
25%     464.662392   470.132132   460.445576   464.145707  7.983848e+06
50%     658.735230   667.131276   651.277974   658.618586  1.432918e+07
75%     777.106674   783.380562   771.121280   777.418303  2.485022e+07
max    1012.900024  1020.500000  1008.500000  1017.500000  4.453421e+08

============================================================
Statistical Summary: HINDUNILVR_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1871.275023  1889.468487  1853.251388  1872.256031  1.770625e+06
std     601.593625   607.352546   596.762576   602.454634  3.917726e+06
min     682.621094   693.332359   678.197686   682.143963  0.000000e+00
25%    1462.100098  1477.667632  1444.273408  1464.081105  1.018394e+06
50%    2057.019531  2080.032519  2028.758524  2058.619140  1.423168e+06
75%    2370.158630  2393.732870  2349.836519  2371.049106  1.968707e+06
max    2939.454590  2945.714793  2882.578420  2931.156105  1.856699e+08

============================================================
Statistical Summary: ICICIBANK_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    664.492658   671.005676   657.718846   664.384310  1.846460e+07
std     390.609187   392.796094   388.257275   390.366202  1.386027e+07
min     181.544952   184.983146   178.318994   179.719730  0.000000e+00
25%     309.750175   316.532782   305.220510   311.269421  1.075295e+07
50%     571.873840   580.433434   562.032662   572.574984  1.486341e+07
75%     932.316284   936.208933   923.795294   931.373438  2.170738e+07
max    1477.201782  1488.514473  1466.782160  1488.514473  2.868577e+08

============================================================
Statistical Summary: INFY_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1021.420114  1031.560176  1011.368838  1021.685205  8.080513e+06
std     492.752058   497.044640   488.390664   492.944325  6.708731e+06
min     346.069702   351.696233   340.760218   348.684818  0.000000e+00
25%     545.978531   554.301424   538.002709   545.798819  4.996143e+06
50%    1154.044312  1165.955057  1147.321483  1156.435878  6.656110e+06
75%    1458.562713  1470.155341  1444.934217  1459.038202  8.961042e+06
max    1942.221191  1948.777171  1920.756459  1938.093361  1.644050e+08

============================================================
Statistical Summary: ITC_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    251.849168   254.384683   249.579566   252.134155  1.717068e+07
std     102.262508   102.952746   101.647345   102.344067  1.711199e+07
min     107.234131   110.693285    98.021826   107.780313  0.000000e+00
25%     174.090652   176.025422   172.668589   174.401203  8.939881e+06
50%     198.690544   201.051703   197.044984   199.214183  1.261085e+07
75%     374.673370   380.708339   371.361618   375.086557  1.967460e+07
max     476.588745   481.830946   474.309479   474.628601  4.318516e+08

============================================================
Statistical Summary: KOTAKBANK_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    306.276594   309.506564   302.934504   306.350472  1.765321e+07
std      84.918065    85.663058    84.262968    84.950911  2.080183e+07
min     126.536163   127.768147   125.592310   126.476556  0.000000e+00
25%     242.637478   246.816181   238.872745   242.901616  9.079605e+06
50%     341.210526   344.341183   337.639429   341.797068  1.376640e+07
75%     368.262436   371.995154   364.745650   368.457209  2.072497e+07
max     453.237457   459.849829   448.562824   456.473702  4.429906e+08

============================================================
Statistical Summary: LT_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1866.018199  1885.836178  1847.471920  1867.264858  2.668586e+06
std    1047.452810  1056.453058  1038.518838  1047.962999  1.909111e+06
min     648.860535   656.273494   610.011890   643.419512  0.000000e+00
25%    1082.896332  1094.809020  1072.616445  1083.583948  1.580207e+06
50%    1373.257812  1394.419184  1358.405605  1380.307885  2.110620e+06
75%    2664.583008  2688.335373  2648.584201  2674.216581  3.059812e+06
max    4418.100098  4440.000000  4371.700195  4415.500000  2.115335e+07

============================================================
Statistical Summary: MARUTI_NS.csv
============================================================

              Close          High           Low          Open        Volume
count   2470.000000   2470.000000   2470.000000   2470.000000  2.470000e+03
mean    8280.942950   8370.387015   8194.204611   8286.505739  7.044838e+05
std     2893.682091   2913.060353   2873.311633   2895.143394  4.873813e+05
min     3132.276367   3171.856182   3121.183177   3138.074074  0.000000e+00
25%     6532.938721   6608.425224   6458.957867   6545.251339  3.883378e+05
50%     7488.995850   7581.055007   7373.692557   7499.556661  5.621900e+05
75%     9678.698242   9766.638114   9539.826095   9649.125591  8.662695e+05
max    17292.000000  17370.000000  17142.000000  17230.000000  4.892962e+06

============================================================
Statistical Summary: NESTLEIND_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    772.338975   780.134687   764.500986   772.782439  1.509265e+06
std     336.208387   338.985756   333.341448   336.486663  1.302199e+06
min     220.951584   223.076567   220.654004   222.197056  0.000000e+00
25%     459.904160   466.431249   456.444190   461.534473  7.920650e+05
50%     815.339966   826.397994   805.791295   817.072025  1.192790e+06
75%    1084.443450  1095.424055  1074.673576  1084.354579  1.816304e+06
max    1355.930542  1367.002411  1343.874580  1353.224129  2.294119e+07

============================================================
Statistical Summary: NTPC_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    160.720419   162.672272   158.852962   160.866458  1.351703e+07
std     101.687435   102.830502   100.579545   101.844420  1.256966e+07
min      59.543129    62.037085    57.049172    58.374088  0.000000e+00
25%      92.453896    93.624240    91.361359    92.588014  6.455952e+06
50%     103.880051   105.056624   102.874417   103.915120  1.021310e+07
75%     207.542896   208.860837   205.455553   207.582811  1.607640e+07
max     425.839874   430.884232   421.612262   428.530251  2.169817e+08

============================================================
Statistical Summary: ONGC_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    132.942932   134.754186   131.307778   133.156081  1.517576e+07
std      62.537150    63.233344    61.814742    62.609742  1.470298e+07
min      40.190529    42.200055    33.492106    39.788623  0.000000e+00
25%      90.798855    92.093353    89.671751    91.014465  6.883600e+06
50%     112.562489   114.179009   111.170261   112.835661  1.080124e+07
75%     153.834393   154.973416   152.201055   153.748411  1.803894e+07
max     307.873627   310.801442   303.729602   309.990661  1.780948e+08

============================================================
Statistical Summary: POWERGRID_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    136.448917   138.075004   134.846886   136.496803  1.435302e+07
std      84.820852    85.766676    83.820246    84.813752  1.285784e+07
min      48.135250    48.668520    47.655319    47.993045  0.000000e+00
25%      72.701328    73.534766    71.886757    72.812196  7.772891e+06
50%      91.672001    94.182819    90.650293    92.498067  1.137145e+07
75%     172.032795   174.035118   169.126767   172.499496  1.699214e+07
max     344.843262   345.598106   337.058457   343.522181  2.743525e+08

============================================================
Statistical Summary: RELIANCE_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    870.386834   879.438488   861.994818   870.926774  1.785488e+07
std     420.060484   423.477548   416.907742   420.291160  1.356882e+07
min     203.784943   206.129571   202.831753   203.357641  0.000000e+00
25%     485.772644   494.043805   475.683857   487.145606  1.017227e+07
50%     949.962708   961.584027   940.191289   951.536846  1.402421e+07
75%    1209.938233  1218.876215  1199.699613  1210.446931  2.046586e+07
max    1592.300049  1611.800049  1578.199951  1593.000000  1.426834e+08

============================================================
Statistical Summary: SBIN_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    438.368651   443.406485   433.466859   438.683902  2.427468e+07
std     236.487555   238.032248   234.723889   236.408920  2.156618e+07
min     139.191803   141.360188   137.899991   140.206791  0.000000e+00
25%     250.725170   254.139227   247.363490   250.988118  1.200204e+07
50%     334.646255   338.290978   330.148011   334.853857  1.691509e+07
75%     569.690079   574.619743   565.792900   571.232396  2.779190e+07
max    1227.800049  1234.699951  1219.699951  1232.000000  2.626771e+08

============================================================
Statistical Summary: SUNPHARMA_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    864.952243   874.981282   855.414490   865.740913  4.892554e+06
std     463.393059   466.425474   459.746538   463.405913  5.347498e+06
min     305.600525   323.964792   293.828532   302.916493  0.000000e+00
25%     489.213905   497.160745   482.705524   490.874989  2.044783e+06
50%     711.783752   720.742207   705.466843   714.976636  3.228232e+06
75%    1102.506775  1109.702477  1093.079099  1100.530896  5.676101e+06
max    1918.210327  1929.678097  1890.993062  1918.505705  8.290621e+07

============================================================
Statistical Summary: TCS_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   2383.258626  2406.671619  2360.743354  2384.308118  2.731429e+06
std     986.674190   994.863326   979.547389   987.382688  2.407816e+06
min     844.116272   859.723915   824.330836   850.443954  0.000000e+00
25%    1561.888001  1586.143049  1537.801801  1568.008829  1.682324e+06
50%    2694.853759  2726.234803  2671.445547  2699.847720  2.283587e+06
75%    3168.928284  3194.412890  3141.319199  3174.332645  3.156769e+06
max    4311.585449  4348.038052  4272.055480  4332.652012  8.806715e+07

============================================================
Statistical Summary: TECHM_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    863.320902   874.192312   852.553611   863.698020  2.869909e+06
std     430.918767   435.588873   426.206811   431.142026  2.082513e+06
min     278.204041   280.532899   263.676571   277.242972  0.000000e+00
25%     494.073006   502.204968   483.752068   494.167563  1.625025e+06
50%     823.565460   836.239568   814.899277   826.251434  2.356704e+06
75%    1223.141998  1240.198729  1211.510691  1223.812801  3.472836e+06
max    1768.400024  1854.000000  1739.900024  1845.000000  3.117145e+07

============================================================
Statistical Summary: TITAN_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean   1875.105931  1895.894972  1853.858904  1875.903726  1.793651e+06
std    1175.351779  1185.338167  1165.022049  1175.743666  1.755794e+06
min     293.463013   296.365721   286.544923   294.140329  0.000000e+00
25%     878.437546   891.987879   865.453619   878.896930  8.547452e+05
50%    1476.362183  1496.622143  1456.742393  1481.802574  1.316840e+06
75%    3052.110351  3073.230930  3024.620865  3053.936449  2.165173e+06
max    4342.600098  4378.399902  4311.799805  4350.000000  2.710010e+07

============================================================
Statistical Summary: ULTRACEMCO_NS.csv
============================================================

              Close          High           Low          Open        Volume
count   2470.000000   2470.000000   2470.000000   2470.000000  2.470000e+03
mean    6421.062767   6492.557100   6352.916867   6425.456982  3.843714e+05
std     2997.977953   3021.353746   2973.108345   2997.688023  3.004184e+05
min     2790.100586   2836.267850   2778.966815   2801.714333  0.000000e+00
25%     3875.705262   3925.665038   3842.148673   3885.198412  2.142110e+05
50%     5585.466309   5688.213819   5505.289493   5586.588898  3.035720e+05
75%     8187.184570   8247.143467   8112.016982   8188.181764  4.623942e+05
max    13052.000000  13110.000000  12986.000000  13089.000000  5.134859e+06

============================================================
Statistical Summary: WIPRO_NS.csv
============================================================

             Close         High          Low         Open        Volume
count  2470.000000  2470.000000  2470.000000  2470.000000  2.470000e+03
mean    170.715304   172.680682   168.911856   170.914922  1.329176e+07
std      70.334159    71.210736    69.629117    70.501147  1.458179e+07
min      74.470154    75.296372    69.521384    72.400360  0.000000e+00
25%     101.042347   102.089338   100.263080   101.218749  6.682293e+06
50%     178.076218   179.621287   177.282766   178.732645  9.690534e+06
75%     234.895573   237.739994   232.759221   235.105159  1.481045e+07
max     333.296661   341.773408   330.755935   333.874098  2.607352e+08

# 07. Unique Value Check

In [9]:
for name, df in datasets.items():
    print("="*60)
    print(f"Unique Values: {name}")
    print("="*60)
    for col in df.columns:
        print(f"{col}: {df[col].nunique()} unique values")

============================================================
Unique Values: ADANIENT_NS.csv
============================================================
Date: 2470 unique values
Close: 2366 unique values
High: 2459 unique values
Low: 2455 unique values
Open: 2452 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: ADANIPORTS_NS.csv
============================================================
Date: 2470 unique values
Close: 2346 unique values
High: 2457 unique values
Low: 2459 unique values
Open: 2439 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: ASIANPAINT_NS.csv
============================================================
Date: 2470 unique values
Close: 2432 unique values
High: 2466 unique values
Low: 2470 unique values
Open: 2465 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: AXISBANK_NS.csv
============================================================
Date: 2470 unique values
Close: 2361 unique values
High: 2462 unique values
Low: 2465 unique values
Open: 2452 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: BAJAJFINSV_NS.csv
============================================================
Date: 2470 unique values
Close: 2444 unique values
High: 2450 unique values
Low: 2454 unique values
Open: 2441 unique values
Volume: 2465 unique values
Ticker: 1 unique values
============================================================
Unique Values: BAJFINANCE_NS.csv
============================================================
Date: 2470 unique values
Close: 2446 unique values
High: 2463 unique values
Low: 2457 unique values
Open: 2447 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: BHARTIARTL_NS.csv
============================================================
Date: 2470 unique values
Close: 2357 unique values
High: 2464 unique values
Low: 2462 unique values
Open: 2453 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: DRREDDY_NS.csv
============================================================
Date: 2470 unique values
Close: 2435 unique values
High: 2456 unique values
Low: 2452 unique values
Open: 2446 unique values
Volume: 2463 unique values
Ticker: 1 unique values
============================================================
Unique Values: EICHERMOT_NS.csv
============================================================
Date: 2470 unique values
Close: 2447 unique values
High: 2462 unique values
Low: 2460 unique values
Open: 2458 unique values
Volume: 2463 unique values
Ticker: 1 unique values
============================================================
Unique Values: HCLTECH_NS.csv
============================================================
Date: 2470 unique values
Close: 2432 unique values
High: 2470 unique values
Low: 2470 unique values
Open: 2468 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: HDFCBANK_NS.csv
============================================================
Date: 2470 unique values
Close: 2416 unique values
High: 2458 unique values
Low: 2459 unique values
Open: 2447 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: HINDUNILVR_NS.csv
============================================================
Date: 2470 unique values
Close: 2436 unique values
High: 2468 unique values
Low: 2465 unique values
Open: 2465 unique values
Volume: 2466 unique values
Ticker: 1 unique values
============================================================
Unique Values: ICICIBANK_NS.csv
============================================================
Date: 2470 unique values
Close: 2362 unique values
High: 2452 unique values
Low: 2463 unique values
Open: 2452 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: INFY_NS.csv
============================================================
Date: 2470 unique values
Close: 2432 unique values
High: 2468 unique values
Low: 2468 unique values
Open: 2467 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: ITC_NS.csv
============================================================
Date: 2470 unique values
Close: 2282 unique values
High: 2465 unique values
Low: 2469 unique values
Open: 2464 unique values
Volume: 2470 unique values
Ticker: 1 unique values
============================================================
Unique Values: KOTAKBANK_NS.csv
============================================================
Date: 2470 unique values
Close: 2405 unique values
High: 2460 unique values
Low: 2463 unique values
Open: 2448 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: LT_NS.csv
============================================================
Date: 2470 unique values
Close: 2438 unique values
High: 2462 unique values
Low: 2465 unique values
Open: 2454 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: MARUTI_NS.csv
============================================================
Date: 2470 unique values
Close: 2459 unique values
High: 2466 unique values
Low: 2462 unique values
Open: 2460 unique values
Volume: 2465 unique values
Ticker: 1 unique values
============================================================
Unique Values: NESTLEIND_NS.csv
============================================================
Date: 2470 unique values
Close: 2458 unique values
High: 2469 unique values
Low: 2468 unique values
Open: 2469 unique values
Volume: 2453 unique values
Ticker: 1 unique values
============================================================
Unique Values: NTPC_NS.csv
============================================================
Date: 2470 unique values
Close: 2179 unique values
High: 2461 unique values
Low: 2466 unique values
Open: 2465 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: ONGC_NS.csv
============================================================
Date: 2470 unique values
Close: 2271 unique values
High: 2466 unique values
Low: 2464 unique values
Open: 2468 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: POWERGRID_NS.csv
============================================================
Date: 2470 unique values
Close: 2272 unique values
High: 2463 unique values
Low: 2466 unique values
Open: 2468 unique values
Volume: 2468 unique values
Ticker: 1 unique values
============================================================
Unique Values: RELIANCE_NS.csv
============================================================
Date: 2470 unique values
Close: 2413 unique values
High: 2461 unique values
Low: 2466 unique values
Open: 2459 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: SBIN_NS.csv
============================================================
Date: 2470 unique values
Close: 2274 unique values
High: 2459 unique values
Low: 2459 unique values
Open: 2452 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: SUNPHARMA_NS.csv
============================================================
Date: 2470 unique values
Close: 2403 unique values
High: 2465 unique values
Low: 2469 unique values
Open: 2468 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: TCS_NS.csv
============================================================
Date: 2470 unique values
Close: 2454 unique values
High: 2469 unique values
Low: 2470 unique values
Open: 2470 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: TECHM_NS.csv
============================================================
Date: 2470 unique values
Close: 2412 unique values
High: 2468 unique values
Low: 2467 unique values
Open: 2463 unique values
Volume: 2469 unique values
Ticker: 1 unique values
============================================================
Unique Values: TITAN_NS.csv
============================================================
Date: 2470 unique values
Close: 2423 unique values
High: 2467 unique values
Low: 2465 unique values
Open: 2463 unique values
Volume: 2467 unique values
Ticker: 1 unique values
============================================================
Unique Values: ULTRACEMCO_NS.csv
============================================================
Date: 2470 unique values
Close: 2441 unique values
High: 2460 unique values
Low: 2466 unique values
Open: 2460 unique values
Volume: 2465 unique values
Ticker: 1 unique values
============================================================
Unique Values: WIPRO_NS.csv
============================================================
Date: 2470 unique values
Close: 2324 unique values
High: 2463 unique values
Low: 2468 unique values
Open: 2467 unique values
Volume: 2469 unique values
Ticker: 1 unique values

# 08. Key Observations
1. Overall there are **30 datasets observed** in the data directory that was obtained from the data ingestion pipeline (ref. to: **root/src/data_ingestion.py**).
2. Accoding to **Dataset Overview**
   * All the datasets are having common number of rows and columns.
   * All datasets with columns/attrutes are having right data-type into it (so there is no type-casting required)
3. According to **Missing Values Analysis** any of datasets are **not having any type of missing values** in it.
4. Accoding to: **Checking Duplicated Values** there are **no any duplicated values** recorded in any individual dataset it means all the **values are unique**.

For Advanced EDA report please refer to:
**root_dir/observations/advanced_eda_report.md**
[Advanced EDA report](../../observations/advanced_eda_report.md)